name: Docs

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build docs (python-3.14, ubuntu-latest)
    runs-on: ubuntu-latest
    env:
      UV_HTTP_TIMEOUT: 900 # max 15min to install deps
    steps:
      - name: Configure GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v6.0.0
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Set up Python 3.14
        run: uv python install 3.14
      - name: Install the project
        run: uv sync --only-group docs
      - name: Build docs with Zensical
        run: uv run --only-group docs zensical build --clean --strict
      - name: Upload GitHub Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: site

  deploy:
    name: Deploy docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.1
