name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      UV_HTTP_TIMEOUT: 900 # max 15min to install deps
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests and generate coverage report
        run: uv run pytest --doctest-modules -v --cov=toyllm --cov-fail-under 0 --cov-report=term --cov-report=xml --cov-report=html toyllm tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: success() && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
